#!/bin/bash

#允许同时跑的任务数为THREAD_NUM
#THREAD_NUM=1

fileIn=$1

if [ "$#" -eq 1  ]
then
    THREAD_NUM=1
else
    THREAD_NUM=$2
fi


#指定分隔符
IFS='
'

#定义描述符为9的FIFO管道
mkfifo .tmp
exec 9<>.tmp
rm -f .tmp

#预先写入指定数量的空格符，一个空格符代表一个进程
for ((i=0;i<$THREAD_NUM;i++))
do
    echo >&9
done

while read line
do
#    echo $line
    #控制进程数：读出一个空格字符，如果管道为空，此处将阻塞
    read -u9
    {
        #打印参数 
        #echo ${arg} 
        #此行代码指定任务提交方法
        echo $line >> .parl_run.$fileIn
        eval $line

        #每执行完一个程序，睡眠3s
        sleep 1
        #控制进程数：一个任务完成后，写入一个空格字符到管道，新的任务将可以执行
        echo >&9
    }&
done < $fileIn
wait
echo "全部任务执行结束"
